steps:
  - label: "Julia v1"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - JuliaCI/julia-test#v1:
      - JuliaCI/julia-coverage#v1:
          codecov: true
    agents:
      queue: "juliagpu"
      cuda: "*"
    timeout_in_minutes: 60
    if: build.pull_request.base_branch == "master" || build.pull_request.base_branch == null

env:
  JULIA_PKG_SERVER: "" # it often struggles with our large artifacts
  # SECRET_CODECOV_TOKEN: ""
