Base.@deprecate(
    train(
        model::MLJFlux.MLJFluxModel,
        chain,
        optimiser,
        optimiser_state,
        epochs,
        verbosity,
        X,
        y,
    ),
    train(
        model::MLJFlux.MLJFluxModel,
        chain,
        optimiser_state,
        epochs,
        verbosity,
        X,
        y,
    ),
    false,
)

Base.@deprecate(
    train_epoch(
        model::MLJFlux.MLJFluxModel,
        chain,
        optimiser,
        optimiser_state,
        X,
        y,
    ),
    train_epoch(
        model::MLJFlux.MLJFluxModel,
        chain,
        optimiser_state,
        X,
        y,
    ),
    false,
)
